/// =============== BEGIN ASSESSMENT HEADER ================
/// @file assn7/Makefile
/// @brief Assignment/ for CS 12 Winter2015
///
/// @author Se Hoon Bang [sbang002@ucr.edu]
/// @date March 12 2015
///
/// @par Enrollment Notes 
/// Lecture Section: 001
/// @par
/// Lab Section: 021
/// @par
/// 
/// @par Plagiarism Section
/// I hereby certify that the code in this file
/// is ENTIRELY my own original work.
// ================== END ASSESSMENT HEADER ===============
// ifstream fin;
    // fin.open(datafile.c_str());
    // if(!fin.is_open())
    // {
    //     cout << "Error opening file";
    //     return false;
    // }
    // string type;
    // while(fin >> type)
    // {
    //     if(type == "<begin_topic>")
    //     {
    //         string SBJ, BDY,art;
    //         int id, child;
    //         vector <int> Children;
    //         char k;
    //         fin.getline(id);
    //         fin.getline(SBJ);
    //         fin.getline(art);
    //         fin >> k;
    //         if(k == ":children:")    
    //         {    
    //             while(k != "\n")
    //             {
    //                 fin.getline(k, 1);
    //                 fin >> child;
    //                 Children.push_back(child);
                    
    //             }
    //         }
    //         fin.getline(BDY,9999999999999,"<")
    //         Topic NEW(art,SBJ,BDY,id);
    //         for(int i = 0; i < Children.size(); i++)
    //         {
    //             NEW.add_child(message_list.at(Children.at(i)));
    //         }
    //         message_list.push_back(NEW);
    //     }
    //     else if(type == "<begin_reply")
    //     {
    //         string SBJ, BDY;
    //         int id;
    //         string trash;
    //         fin.getline(id);
    //         fin.getline(SBJ);
    //         fin.getline(BDY,9999999999999,"<")
    //         fin.getline(trash);
    //         Reply NEW(current_user,SBJ,BDY,id);
    //         message_list.push_back(NEW);
    //     }
    // }